### ISSUE TITLE
separate logical systems or just independent datasets and perspectives?

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/exchange#2]
> If exchanges happen between agents in different systems, then a resource transfer needs to be separated into a Give event (might be called a Shipment) in one system and a Take event (might be called a Receipt) in the other system.
> 
> If the agents operate in the same logical system, then a resource transfer can just be a transfer - a single event where the resource moves from the Giver to the Taker - although the Giver and the Taker will have different views of the same event.

Since we all operate in present time as part of **ecosystem of planet Earth**, one can consider everything as single _logical system_. On the other side, since we use decentralized _information system_ possibly even full P2P, we should anticipate for that in modeling. In other words, each exchange or event with multiple peers (Agents) involved, will have multiple sources of 'truth' all possibly expressing same event from different perspective (eg. Give/Take, Lend/Borrow etc.).

See also
- https://github.com/mnot/I-D/issues/39#issuecomment-89789736
- https://github.com/jasnell/w3c-socialwg-activitystreams/issues/180#issuecomment-119541477

**Comment by bhaugen** [comment]
@elf-pavlik - re multiple sources of truth: the purpose of a conversation for action is to come to enough agreement to move ahead to do the actions. So everybody involved will have different views, but they need some critical, definable intersection.

And then, if these actions happen in a resource flow network, it will be useful to know what resources flowed where.

Changing the subject to IPO tables and processes for a bit, let's say one output of a process is a lot of manure. What happens to it next? 

Some people around us are conducting a conversation for action between a company that has a CAFO (Confined Animal Feeding Operation) that puts manure into big lagoons, and the local government, and themselves as concerned citizens.

One of the inputs to the CAFO process is antibiotics, exchanged with pharmaceutical companies. The animals are filled with antibiotics because they get sick in the CAFO environment. And the antibiotics are also an output, mixed in with the manure.

The antibiotics then breed resistant bacteria, which end up in hospitals, killing people, because the common antibiotics no longer work.

**Comment by elf-pavlik** [comment]
> So everybody involved will have different views, but they need some critical, definable intersection.

Even when we agree on something, when we don't use online silo, this common agreement will need to live in multiple places, and will require way to verify that all parties if fact agreed. Even in paper based contracts, each side gets it's own copy + may involve some notary service. IMO we need similar pattern for online contracts, which accommodates need of combining information from multiple data spaces to have valid assertions.

**Comment by bhaugen** [comment]
Yes to all that. Plus, each state change in a conversation for action
between independent agents working in different computation spaces requires
a distributed consensus protocol. I guess blockchains are where peoples'
heads are at now, but those are slow, computationally expensive, and
subject to re-centralization (mining pools). Paxos variants are an
alternative.

**Comment by elf-pavlik** [comment]
I don't propose blockchains here, we could look at technologies like [Secure Scuttlebutt](https://github.com/ssbc) (ping @ahdinosaur) But I still see need to connect equivalent assertions from multiple parties, as discussed in https://github.com/openvocab/agent/issues/7

**Comment by bhaugen** [comment]
I'm good with Secure Scuttlebutt. Forgot that one. Sorry, Mikey...old man,
bad memory.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/2.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
