### ISSUE TITLE
Custody of resources (especially during transfers and transportation)

### ISSUE THREAD

**Issue by gcassel** [valueflows/exchange#31]
How about we generally assume (without bothering to document) that vf:Owner has _custody_ of a resource, unless custody is formally delegated to someone else?

(For instance, an Owner giving custody of a resource to a delivery service, and then transferring ownership to a new owner/ buyer upon the signing of a receipt of delivery-- implicitly terminating the temporary custody of the delivery service).

(Or, a moving company assumes custody of a piece of furniture while transporting it to a new location, without ownership ever changing.)

**Comment by bhaugen** [comment]
I think that is generally true, but we have been trying to move away from mandating the concept of ownership as we have moved away from mandating a lot of business-as-usual practices. So I like the idea of custody (or some better word that denotes a set of rights and responsibilities) as one possible substitute. I think many resources need somebody to be responsible for them.

I also think, @gcassel , that this slot will end up  evolving into one of your agreement things...not sure if that would be part of VF or not. I think it is in the same realm as contracts: used a lot in economic networks, but how deep do we want to get into the details?

In REA, a Contract is a bundle of Commitments, which seems like enough. We could call it Agreement instead of Contract to avoid arguments about legality.

**Comment by gcassel** [comment]
I definitely don't like mandating the concept of ownership, either, @bhaugen --   I was reacting to others' use of the term vf:Owner.   I think it would make sense to allow agents to designate any combinations of rights and responsibilities that they wish to assign to resources.     

You could be right too that this should all be related to formal agreements, and not part of VF per se.   It seems quite possible to separate these areas of conceptual development in a complementary, and perhaps modularly interoperable, way.   

I was asked to create this issue for reference's sake.  I probably should've pointed that out above!  Of course, everyone should feel free to comment if they desire to.

**Comment by bhaugen** [comment]
> I definitely don't like mandating the concept of ownership, either, 

I figured you didn't, but since all this chatter is "on the record", and we have had increased incidents of arguments in which some variation on "legal" appeared, I wanted to pop in for a bit.

But yeah, whatever agreements people want to make.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/31.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
