### ISSUE TITLE
Revised Exchange model for comment

### ISSUE THREAD

**Issue by bhaugen** [valueflows/exchange#34]
https://docs.google.com/document/d/1UkNwicYo2JjeChcXAlvlVPz2gFlZDr9KYJP_GBKGOo8/edit?usp=sharing

Comment here or on the doc?

**Comment by bhaugen** [comment]
P.S. this issue and document were created as part of a conversation with the REA community. They may respond in an email thread, on the document, or here. Probably not here, but I want to give them the opportunity. 

Of course, anybody else who sees this can respond, too.

**Comment by elf-pavlik** [comment]
Would it make sense to mention use cases like - exchanging *work* for *usage* where 'transferring ownership over resources' doesn't seem to fit that well?

**Comment by bhaugen** [comment]
Yes. I plan to write up use cases about work and services where ownership transfer doesn't make sense, for another REA community response, assuming we get any responses to this first one.

**Comment by elf-pavlik** [comment]
I think *usage* fits here also very well and don't have peculiarities of *work* (should we consider 'work force' of agent doing the work as resource) and *servce* (possibly event that directly connects two processes - not a resource appearing on output of one and input of other one)

**Comment by bhaugen** [comment]
@elf-pavlik what do you think are the peculiarities of work?

(I also consider human labor to be different from other process inputs in a lot of ways. Just wondering which ways you had in mind.)

**Comment by elf-pavlik** [comment]
1. I think all other events reference a particular resource which they affect in some way, *work* currently doesn't make that resource explicit and it seems like implying *the work force of the person who 'provided' it*
2. For most events happening as inputs, we can trace back some previous outputs that made it possible, for *use* of equipment we have all kind of events on that equipment *produce*, *unload*, *improve* and possibly other. For *work* events we currently don't have clear way to trace buck such previous outputs which made that work possible.

I think eventually we may need to recognize three aspects of any given Person:
* agent - can make agreements and builds trust & reputation
* resource - can have *improve* events, as well as *load* and *unload*
* process - personal livelihood project, which includes all the smaller sub-processes like work sessions, getting oneself transported etc. they include *consume* on meals *use* on bathrooms etc.

I also consider modeling each skill as a resource which only person having that skill can *own*, then work becomes more of a process bound to the individual in which person *use* those skills ('improving' them like *cite*) and this process provides service as input to other processes (instead of simple *work* event). I think above fits more https://github.com/valueflows/valueflows/issues/174

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/exchange/-/issues/34.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
